#!/bin/bash

font=Lazer84
font="Solomon's-Key-True-Type-Smoose"
font="Karmatic-Arcade"
font=Game-Played
font=Arcade-Interlaced
font=Arcade-Rounded
font=Arcade-Normal

#source systems

#primary="#e388ff"
#secondary="#C000C0"

#primary="#FFCC00"
#secondary="#ccB000"
font=Arcade-Normal
primary="#FF8C00"
secondary="#FF4500"
#primary=green
#secondary=red
#primary="#AAAAAA"
#secondary="#444444"
primary="#66ef0d"
secondary="#46a10b"

primary="#FFFFFF"
secondary="#888888"

primary="${primary:-#E60000}"
secondary="${secondary:-#0000FF}"

source ../scripts/systems

for system in ${!system_name[@]} ; do
	systemtext="${system_name[$system]}"

	echo "$systemtext"

	convert \
		-size 240x20 \
		xc:transparent \
		-font "$font" \
		-fill "$secondary" \
		-pointsize 16 \
		-gravity center \
		-annotate +2+2 "$systemtext" \
		-flatten \
		-fill "$primary" \
		-pointsize 16 \
		-gravity center \
		-annotate +0+0 "$systemtext" \
		-flatten \
			../logo/small/$system.png



	if [ ! -f ../system/small/$system.png ]; then
		convert \
			../system/big/$system.png \
			-fuzz 1% \
			-trim +repage \
			-scale "128x84>" \
			-background none .\
				../system/small/$system.png \
	fi
done
