#!/bin/bash

# image width
allx="320"
# image height
ally="240"
# roundrectangle x_offset,y_offset x_size,y_size x_round,y_round

##############################################################################
# nice 2px wide border with 10px buffer on sides
##############################################################################
curve="10"
thick="2"
outerx="10"
outery="2"

if [ -f colorscheme ]; then
	source colorscheme
fi

# FBA colors
#	-fill "#82000E" \
#	-fill "#F2931C" \

# Nintendo Colors
#	-fill "#0000ff" \
#	-fill "#00cc00" \

primary="${primary:-#E60000}"
secondary="${secondary:-#0000FF}"

convert \
	-size ${allx}x${ally} \
	xc:black \
	-fill "$primary" \
	-draw "roundrectangle $outerx,$outery $[ $allx - $thick - $outerx ],$[ $ally - $thick ] $curve,$curve" \
	-fill "$secondary" \
	-draw "roundrectangle $[ $outerx + 2 ],$[ $outery + 2 ] $[ $allx - ($thick * 2) - $outerx ],$[ $ally - ($thick * 2) ] $[ $curve + 2 ],$[ $curve + 2 ]" \
	-fill black \
	-draw "roundrectangle $[ $outerx + 4 ],$[ $outery + 4 ] $[ $allx - ($thick * 3) - $outerx ],$[ $ally - ($thick * 3) ] $[ $curve + 4 ],$[ $curve + 4 ]" \
	genericbackground.png

exit 

##############################################################################
# cool color on opposite sides look
##############################################################################

convert \
	-size ${allx}x${ally} \
	xc:black \
	-fill "#0000ff" \
	-draw "roundrectangle 5,5 315,235 10,10" \
	-fill "#00cc00" \
	-draw "roundrectangle 7,7 315,235 10,10" \
	-fill black \
	-draw "roundrectangle 7,7 313,233 10,10" \
	genericbackground.png

##############################################################################
# fill the screen
##############################################################################

# how much to change per level
change="2"
# how much black border around the edge
largeoff="5"

largex="$[ $allx - $largeoff ]"
largey="$[ $ally - $largeoff ]"

medoff="$[ $largeoff + $change ]"
smalloff="$[ $medoff + $change ]"

medx="$[ largex - $change ]"
medy="$[ largey - $change ]"

smally="$[ largey - ($change * 2) ]"
smallx="$[ largex - ($change * 2) ]"

convert \
	-size ${allx}x${ally} \
	xc:black \
	-fill "#0000ff" \
	-draw "roundrectangle $largeoff,$largeoff $largex,$largey $largeoff,$largeoff" \
	-fill "#00cc00" \
	-draw "roundrectangle $medoff,$medoff $medx,$medy $medoff,$medoff" \
	-fill black \
	-draw "roundrectangle $smalloff,$smalloff $smallx,$smally $smalloff,$smalloff" \
	genericbackground.png

