#!/bin/bash

# TODO

[ "$1" ] && cd "$1"
echo "##############################################################################"
pwd
echo "##############################################################################"

set -x
transparency=0.5
transparent=/tmp/transparent-$(date +%s).$$.png
black=/tmp/black-$(date +%s).$$.png
logotiny=/tmp/logotiny-$(date +%s).$$.png
upperright=/tmp/upperright-$(date +%s).$$.png


convert -size 320x240 xc:black $black
convert system-big.png -fuzz 1% -trim +repage -scale 320x240 system.png
convert logo-big.png -fuzz 1% -trim +repage -scale x50 logo.png
convert logo-big.png -fuzz 1% -trim +repage -scale 130x30 $logotiny
convert -size 130x30 xc:transparent  $logotiny -gravity center -composite $upperright
convert system.png -resize 240x180 -alpha set -channel A -evaluate Multiply $transparency +channel $transparent
convert $black $transparent -gravity center -composite $upperright  -gravity northeast -geometry +1+1 -composite background.png

rm -f $transparent $logotiny $upperright $black

exit
#!/bin/bash -x

black=/tmp/black-$(date +%s).$$.png
transparent=/tmp/transparent-$(date +%s).$$.png

convert -size 320x240 xc:black $black
convert system-big.png -fuzz 1% -trim +repage -scale 320x240 system.png
convert logo-big.png -fuzz 1% -trim +repage -scale x50 logo.png
convert system.png -alpha set -channel A -evaluate Multiply 0.25 +channel $transparent.png
convert $transparent.png logo.png -gravity northeast -geometry +3+3 -composite background.png

exit
rm -f $black $transparent
